# 1。 一定要有缩进
# 2. 区分大小写
# 3. 值和冒号后需要有一个空格
# 所有配置： https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
server:
  port: 8090

#bootstrap.yaml:
#  加载优先级： bootstarp > application
#  常用性： application > bootstrap
#使用场景：
#application.yml 主要用于 springboot 项目配置
#bootstrap.yml：
#  SpringCloud
#  加密解密
#  固定参数

app:
  name:
    xxx:
      yyy:
        zzz: imooc

self:
  custom:
    config:
      sdkSecrect: abc123
      host: https://www.imooc.com
      port: ${server.port}

spring:
  datasource:  #数据源相关的配置节点
    type: com.zaxxer.hikari.HikariDataSource  #数据源类型
    #type: com.alibaba.druid.pool.DruidDataSource # 引入自定义的 druid 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver  #MySql 驱动  Old: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imooc-springboot-learn?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: Admin_password123
    hikari:
      connection-timeout: 30000 #等待连接池分配连接的最大时长 （毫秒），超过这个时长还没有可用的连接发生SQLException， 默认：30秒
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长 （毫秒）， 超时则被释放 （retired）， 默认： 10 分钟
      pool-name: DataSourceHikariCP # 连接池名字
      max-lifetime: 1800000 #连接池的生命时长 （毫秒），超时而且没被使用则被释放 （retired），默认：30分钟 1800000ms
      connection-test-query: SELECT 1 # 测试语句
  servlet:
    multipart:
      max-file-size: 300KB # 文件上传最大限制，设置最大值，不能超过，否则报错
      max-request-size: 2MB # 文件最大请求限制，用于批量
  # 改变默认更目录 static
#  mvc:
#    static-path-pattern: /abc/**
  banner:
    image:
      location: classpath:banner/dog.jpeg
      pixelmode: block #图片转 block
    # 也可以自定义txt (图片转 txt: https://degraeve.com/img2txt.php)
    # location: classpath:banner/banner.txt
# MyBatis 相关的配置
mybatis:
  type-aliases-package: com.imooc.pojo # 所有数据库表逆向后所一一映射的实体类 Entity/Bean/POJO
  mapper-locations: classpath:mappers/*.xml # 所有mapper映射的文件所在目录位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 mybatis 的日志实现，可以在控制台打印输入 sql 语句，（不适用于 Prod 环境, 因为日志庞大）
# 通用 mapper 配置
mapper:
  mappers: org.example.my.mapper.MyMapper  # 所有 Mapper 都需要实现的接口
  not-empty: false # 在进行数据库操作的时候，判断一个属性是否为空的时候，是否需要自动追加不为空字符串的判断
                  # username != null  不需要 username != ""
  identity: MYSQL
# 分页插件助手的配置
pagehelper:
    helper-dialect: mysql
    support-methods-arguments: true
